CREATE TABLE [dbo].[PurchaseDetail] (
    [PurchaseDetailId]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [PurchaseId]           BIGINT         NOT NULL,
    [ProductId]            BIGINT         NOT NULL,
    [OrderedQty]           INT            NOT NULL,
    [OrderComments]        NVARCHAR (500) NULL,
    [Price]                MONEY          CONSTRAINT [DF_PurchaseDetail_Price] DEFAULT ((0)) NOT NULL,
    [ReceivedQty]          INT            NULL,
    [BillingAmount]        MONEY          NULL,
    [BillingTaxPercentage] FLOAT (53)     NULL,
    [BillingTaxAmount]     MONEY          NULL,
    [ShippingAmount]       MONEY          NULL,
    [ReceiveRemarks]       NVARCHAR (255) NULL,
    [ActualAmount]         MONEY          NULL,
    [ActualTaxPercentage]  FLOAT (53)     NULL,
    [ActualTaxAmount]      MONEY          NULL,
    [POAdjustComments]     NVARCHAR (250) NULL,
    [Status]               NVARCHAR (25)  NULL,
    [CreatedBy]            BIGINT         NULL,
    [CreatedDate]          SMALLDATETIME  NULL,
    [ReceivedBy]           BIGINT         NULL,
    [ReceivedDate]         SMALLDATETIME  NULL,
    [AdjustedBy]           BIGINT         NULL,
    [AdjustedDate]         SMALLDATETIME  NULL,
    CONSTRAINT [PK_PurchaseDetail] PRIMARY KEY CLUSTERED ([PurchaseDetailId] ASC),
    CONSTRAINT [FK_PurchaseDetail_Product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([ProductId]),
    CONSTRAINT [FK_PurchaseDetail_Purchase] FOREIGN KEY ([PurchaseId]) REFERENCES [dbo].[PurchaseHeader] ([PurchaseId])
);

